name: "Release Vuepress docs"
description: "Simple release your vuepress docs!"
author: "Veaba"
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x $GITHUB_ACTION_PATH/deploy/build.sh
        bash $GITHUB_ACTION_PATH/deploy/build.sh
      shell: bash
branding:
  icon: "tag"
  color: "gray-dark"
