name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
    - name: checkout 
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run build
        CI: true
